### ISSUE TITLE
No longer working after July 15?

### ISSUE THREAD

**Issue by bondjimbond** [yorkulibraries/YUDLbot#6]
After July 15, the bot has stopped working. Now running YUDLbot.py throws the following error:

>   File "YUDLbot.py", line 12, in <module>
>     docs = data["response"]["docs"]
> TypeError: 'int' object has no attribute '__getitem__'

Could this be due to credentials expiring, a change in the way the Twitter API provides data, or something else?

**Comment by bondjimbond** [comment]
This is the Solr query I had been using, successfully until now:
`SOLR_DATA = 'http://localhost:8080/solr/select?q=(RELS_EXT_hasModel_uri_ms:("info:fedora/ir:thesisCModel" OR "info:fedora/ir:citationCModel" OR "info:fedora/islandora:sp_pdf" OR "info:fedora/islandora:sp-audioCModel" OR "info:fedora/islandora:bookCModel" OR "info:fedora/islandora:newspaperCModel" OR "info:fedora/islandora:sp_basic_image" OR "info:fedora/islandora:sp_large_image_cmodel" OR "info:fedora/islandora:sp_videoCModel"))&fl=PID,mods_titleInfo_title_ms,RELS_EXT_isViewableByRole_literal_ms&fq=RELS_EXT_isViewableByRole_literal_ms:"anonymous user" OR ((*:* -RELS_EXT_isViewableByUser_literal_ms:[* TO *]) AND (*:* -RELS_EXT_isViewableByRole_literal_ms:[* TO *]))&wt=json&indent=true&rows=50000'`

Now I get the following response: 

> Traceback (most recent call last):
>  File "arcabot.py", line 14, in <module>
>    docs = data["response"]["docs"]
> TypeError: 'int' object has no attribute '__getitem__'

Any idea what might be the problem here? Running the query in localhost:8080/solr is successful.
